version: "3.8"

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d users_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  user_service:
    build: ./user_service
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/users_db
    depends_on:
      db:
        condition: service_healthy  # Așteaptă ca db să fie sănătos
    volumes:
      - ./user_service:/user_service
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

volumes:
  db_data:
